server {
    listen 80;

    # Prefect API (WebSocket inclus)
    location /api {
        proxy_pass http://prefect-server:4200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # dbt docs statiques
    location /dbt-docs/ {
        alias /var/www/dbt-docs/;
        index index.html;
    }

    # FastAPI (systemd sur le host, port 8000)
    location ~ ^/(gold|overview|health|metrics|docs|openapi\.json) {
        proxy_pass http://10.132.0.2:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Grafana
    location /grafana/ {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Prefect UI (auth basic)
    location / {
        auth_basic "Prefect - PEA-PME";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://prefect-server:4200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
